services:
  dev:
    container_name: kaggle
    build:
      context: .
      dockerfile: Dockerfile
    shm_size: '64gb'
    volumes:
      - type: bind
        source: .
        target: /workspace
      - type: volume
        source: venv
        target: /workspace/.venv
    working_dir: /workspace
    tty: true
volumes:
  venv:
